### PR TITLE
case sensitiveness

### LINKED ISSUE #9: non-regex lists handle case sensitivity in a confusing way
Having one of the following constellations causes the plugin to not allow addresses, which are whitelisted:

a) list says `FOO@example.com`, client says `FOO@example.com`
b) list says `foo@example.com`, client says `FOO@example.com`

while these will be allowed:

c) list says `FOO@example.com`, client says `foo@example.com`
d) list says `foo@example.com`, client says `foo@example.com`

This is because currently [`load_file()`](https://github.com/haraka/haraka-plugin-access/blob/2d183ae385384abef2c68eae5a23d7d6fd15214b/index.js#L494) converts all lists to lowerCase, but the checks do not convert the address given by the client (except for [`rdns_access`](https://github.com/haraka/haraka-plugin-access/blob/2d183ae385384abef2c68eae5a23d7d6fd15214b/index.js#L237)). Case a) vs. c) is particularly confusing.

I'd like to change this so that case is ignored in for all methods and all checks, by removing the extra code in `rdns_access` and adding a simple `address.toLowerCase()` to `in_list()`, as well as tests, ofc.
Since the RFC allows for local part of a mail address to be case sensitive, this may be a breaking change in some setups. However, I suspect that most of those setups would already be broken by behavior a) (`FOO != FOO`). If you are concerned about this, the new behavior may be hidden behind a config flag.

Please let me know what you think. I am happy to code up a PR for this once we reach a consensus about the "right" way to do this. :)

### PR DESCRIPTION
**Pull request by luto**
Fixes #9, see the issue for a full explanation and examples.

This (https://github.com/haraka/haraka-plugin-access/commit/a2b33c4b108f7149da002e8673a07de898211a6f) also fixes the config dir mock, which hasn't been working from my point of view. Please see the commit message for details.

Let me know what you think and if something needs to be changed! :)

### CODE REVIEW

**Comment by luto** [comment]
The tests are admittedly a little sparse, but it tests the primitives (`in_list`, `in_re_list`) as well as an example higher-level one. If you want I can add an uppercase mail address to each and every test, but I am not sure if we gain something from that.

**Review by msimerson — APPROVED** [review]
Looks good to me. Would you mind also updating the changes while and bumping the version in package.json?

**Review by msimerson — CHANGES_REQUESTED** [review]
Also, there are two lint errors that prevent the Travis tests from passing. Please correct those as well.

**Comment by luto** [comment]
rebased onto the current master, added Changes.md, bumped version, fixed linting :)

**Review by msimerson — APPROVED** [review]
LGTM

**Comment by msimerson** [comment]
````
$ npm publish
+ haraka-plugin-access@1.1.1
````

**Comment by luto** [comment]
woop woop! thank you :)

**Pull request merged**
